# Generated by Django 5.0.6 on 2024-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('task', models.TextField(verbose_name='task')),
                ('status', models.TextField(max_length=50, verbose_name='status')),
                ('priority', models.CharField(max_length=50, verbose_name='priority')),
                ('deadlines', models.DateTimeField(max_length=50, verbose_name='deadlines')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
