# Generated by Django 5.0.6 on 2024-09-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_user',
            field=models.CharField(default=1, max_length=50, verbose_name='id user'),
            preserve_default=False,
        ),
    ]
