# Generated by Django 5.0.6 on 2024-07-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='deadlines',
            field=models.CharField(default=1, max_length=50, verbose_name='Срок сдачи'),
            preserve_default=False,
        ),
    ]
