version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: trudibre_admin
      POSTGRES_PASSWORD: 1111
    ports:
      - "5433:5432"
      
  web:
    build: .
    command: >
      sh -c "sleep 5 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://trudibre_admin:1111@db:5432/taskmanager



